-- MySQL Script generated by MySQL Workbench
-- Mon Mar 21 13:16:45 2016
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema djantoli
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema djantoli
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `djantoli` DEFAULT CHARACTER SET utf8 ;
USE `djantoli` ;

-- -----------------------------------------------------
-- Table `djantoli`.`tranche_age`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `djantoli`.`tranche_age` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `valeur` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `djantoli`.`questionnaire`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `djantoli`.`questionnaire` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `tranche_age_id` INT NOT NULL,
  `titre` VARCHAR(45) NULL,
  `text_introduction` TEXT NULL,
  `text_conclusion` TEXT NULL,
  `created_at` DATETIME NULL,
  `updated_at` DATETIME NULL,
  `activated` TINYINT(1) NULL DEFAULT 1,
  PRIMARY KEY (`id`, `tranche_age_id`),
  INDEX `fk_questionnaire_tranche_age1_idx` (`tranche_age_id` ASC),
  CONSTRAINT `fk_questionnaire_tranche_age1`
    FOREIGN KEY (`tranche_age_id`)
    REFERENCES `djantoli`.`tranche_age` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `djantoli`.`theme`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `djantoli`.`theme` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `questionnaire_id` INT NOT NULL,
  `nom` VARCHAR(45) NULL,
  `numOrdre` INT NULL,
  PRIMARY KEY (`id`, `questionnaire_id`),
  INDEX `fk_theme_questionnaire1_idx` (`questionnaire_id` ASC),
  CONSTRAINT `fk_theme_questionnaire1`
    FOREIGN KEY (`questionnaire_id`)
    REFERENCES `djantoli`.`questionnaire` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `djantoli`.`question`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `djantoli`.`question` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `theme_id` INT NOT NULL,
  `questionnaire_id` INT NOT NULL,
  `label` VARCHAR(255) NULL,
  `text_aide` VARCHAR(255) NULL,
  `numOrdre` INT NULL,
  `created_at` DATETIME NULL,
  `updated_at` DATETIME NULL,
  `activated` TINYINT(1) NULL DEFAULT 1,
  PRIMARY KEY (`id`, `theme_id`, `questionnaire_id`),
  INDEX `fk_question_questionnaire1_idx` (`questionnaire_id` ASC),
  INDEX `fk_question_theme1_idx` (`theme_id` ASC),
  CONSTRAINT `fk_question_questionnaire1`
    FOREIGN KEY (`questionnaire_id`)
    REFERENCES `djantoli`.`questionnaire` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_question_theme1`
    FOREIGN KEY (`theme_id`)
    REFERENCES `djantoli`.`theme` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `djantoli`.`reponse_possible`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `djantoli`.`reponse_possible` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `question_id` INT NOT NULL,
  `label` TEXT NOT NULL,
  PRIMARY KEY (`id`, `question_id`),
  INDEX `fk_reponse_possible_question1_idx` (`question_id` ASC),
  CONSTRAINT `fk_reponse_possible_question1`
    FOREIGN KEY (`question_id`)
    REFERENCES `djantoli`.`question` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `djantoli`.`ponderation`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `djantoli`.`ponderation` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `reponse_possible_id` INT NOT NULL,
  `valeur` INT NULL,
  PRIMARY KEY (`id`, `reponse_possible_id`),
  INDEX `fk_ponderation_reponse_possible1_idx` (`reponse_possible_id` ASC),
  CONSTRAINT `fk_ponderation_reponse_possible1`
    FOREIGN KEY (`reponse_possible_id`)
    REFERENCES `djantoli`.`reponse_possible` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `djantoli`.`localisation`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `djantoli`.`localisation` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `valeur` VARCHAR(65) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `djantoli`.`apprenant`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `djantoli`.`apprenant` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `questionnaire_id` INT NOT NULL,
  `localisation_id` INT NOT NULL,
  PRIMARY KEY (`id`, `questionnaire_id`, `localisation_id`),
  INDEX `fk_apprenant_questionnaire_idx` (`questionnaire_id` ASC),
  INDEX `fk_apprenant_localisation1_idx` (`localisation_id` ASC),
  CONSTRAINT `fk_apprenant_questionnaire`
    FOREIGN KEY (`questionnaire_id`)
    REFERENCES `djantoli`.`questionnaire` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_apprenant_localisation1`
    FOREIGN KEY (`localisation_id`)
    REFERENCES `djantoli`.`localisation` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `djantoli`.`reponse`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `djantoli`.`reponse` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `apprenant_id` INT NOT NULL,
  `question_id` INT NOT NULL,
  `reponse_possible_id` INT NOT NULL,
  PRIMARY KEY (`id`, `apprenant_id`, `question_id`, `reponse_possible_id`),
  INDEX `fk_reponse_question1_idx` (`question_id` ASC),
  INDEX `fk_reponse_reponse_possible1_idx` (`reponse_possible_id` ASC),
  INDEX `fk_reponse_apprenant1_idx` (`apprenant_id` ASC),
  CONSTRAINT `fk_reponse_question1`
    FOREIGN KEY (`question_id`)
    REFERENCES `djantoli`.`question` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_reponse_reponse_possible1`
    FOREIGN KEY (`reponse_possible_id`)
    REFERENCES `djantoli`.`reponse_possible` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_reponse_apprenant1`
    FOREIGN KEY (`apprenant_id`)
    REFERENCES `djantoli`.`apprenant` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `djantoli`.`critere`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `djantoli`.`critere` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `apprenant_id` INT NOT NULL,
  `nbr_enfant` INT NULL,
  `age_cadet` INT NULL,
  `age_aine` INT NULL,
  PRIMARY KEY (`id`, `apprenant_id`),
  INDEX `fk_critere_apprenant1_idx` (`apprenant_id` ASC),
  CONSTRAINT `fk_critere_apprenant1`
    FOREIGN KEY (`apprenant_id`)
    REFERENCES `djantoli`.`apprenant` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `djantoli`.`bonne_reponse`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `djantoli`.`bonne_reponse` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `reponse_possible_id` INT NOT NULL,
  PRIMARY KEY (`id`, `reponse_possible_id`),
  INDEX `fk_bonne_reponse_reponse_possible1_idx` (`reponse_possible_id` ASC),
  CONSTRAINT `fk_bonne_reponse_reponse_possible1`
    FOREIGN KEY (`reponse_possible_id`)
    REFERENCES `djantoli`.`reponse_possible` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `djantoli`.`niveau`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `djantoli`.`niveau` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `valeur` INT NOT NULL,
  `tranche_age_id` INT NOT NULL,
  PRIMARY KEY (`id`, `tranche_age_id`, `valeur`),
  INDEX `fk_niveau_tranche_age1_idx` (`tranche_age_id` ASC),
  CONSTRAINT `fk_niveau_tranche_age1`
    FOREIGN KEY (`tranche_age_id`)
    REFERENCES `djantoli`.`tranche_age` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
